### ISSUE TITLE
TextBox completion % not showing in proper location while in 80 cols mode

### ISSUE THREAD

**Issue by 4mig4** [tboox/ltui#10]
TextBox completion % not showing in proper location while in 80 cols mode.

![Screenshot from 2020-05-07 13-12-55](https://user-images.githubusercontent.com/3671074/81254012-efa63d00-9064-11ea-8e5e-cae45f42b6f6.png)

**Comment by waruqi** [comment]
I drew a scrollbar instead of 'xx%'
