### ISSUE TITLE
输入框只能输入一次

### ISSUE THREAD

**Issue by kof98765** [tboox/ltui#11]
### 描述问题

输入框只能输入一次，再次点击输入框不能修改内容，只能选项yes or no

### 期待的结果

输入错误后，能再次修改

### 相关环境
嵌入式linux下，使用ssh登陆启动
ubuntu也有一样的问题

**Comment by waruqi** [comment]
按tab键试试，切回输入框

**Comment by kof98765** [comment]
切不回去的

**Comment by waruqi** [comment]
你先凑活着用吧，等回头有时间我改进下

**Comment by waruqi** [comment]
我修复了，更新到2.0试试
