### ISSUE TITLE
运行测试程序报错

### ISSUE THREAD

**Issue by huguanghui** [tboox/ltui#24]
### 描述问题

$ xmake run test dialog
/home/ubuntu/.xmake/packages/l/lua/5.4.1/531f88cff3a64da0aa3fb05ee281ab7d/bin/lua: error loading module 'ltui.lcurses' from file './build/libltui.so':
        ./build/libltui.so: undefined symbol: lua_checkstack
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        ./src/ltui/curses.lua:27: in main chunk
        [C]: in function 'require'
        ./src/ltui/application.lua:26: in main chunk
        [C]: in function 'require'
        ./src/ltui.lua:26: in main chunk
        [C]: in function 'require'
        tests/dialog.lua:27: in main chunk
        [C]: in ?
error: execv(/home/ubuntu/.xmake/packages/l/lua/5.4.1/531f88cff3a64da0aa3fb05ee281ab7d/bin/lua tests/dialog.lua) failed(1)

### 相关环境

 Ubuntu 18.04.4 LTS x86_64

### 其他信息

ltui和lcurses之前未安装, xmake运行自动安装的

**Comment by waruqi** [comment]
默认用的lua 我没限制版本，可能高版本 已经没 lua_checkstack 这个接口了，一种方式，你可以切到 luajit 版本，另外一种方式，改线 xmake.lua 切到低版本 lua 

```console
xmake f --luajit=y -c
xmake -r
xmake r test dialog
```
