### ISSUE TITLE
Problems Running frontpage window example

### ISSUE THREAD

**Issue by tuxd3v** [tboox/ltui#3]
Hello, I installed ltui,
And I run the example from the front page, 

I get this message:
`/usr/bin/lua: error loading module 'ltui.lcurses' from file '/usr/local/lib/lua/5.3/ltui.so':
	/usr/local/lib/lua/5.3/ltui.so: undefined symbol: ESCDELAY
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	/usr/local/share/lua/5.3/ltui/curses.lua:31: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.3/ltui/application.lua:30: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.3/ltui.lua:31: in main chunk
	[C]: in function 'require'
	./curses:5: in main chunk
	[C]: in ?`

ltui version installed:
`# luarocks list ltui

Installed rocks:
----------------

ltui
   1.2-1 (installed) - /usr/local/lib/luarocks/rocks`

Can you help me?
Thanks in Advance
Regards

**Comment by waruqi** [comment]
I have fixed it, you can reinstall and try it again.  ltui 1.3 for luarocks
