### ISSUE TITLE
can not install ltui on ubuntu 22.04

### ISSUE THREAD

**Issue by laoshaw** [tboox/ltui#38]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
 luarocks install --local ltui

### Expected behavior
install without errors

### Error output
If applicable, please add verbose the errors output to help us analyze your problem.

Installing https://luarocks.org/ltui-2.8-1.rockspec
Cloning into 'ltui'...
fatal: Remote branch v8.7 not found in upstream origin
Error: Failed cloning git repository.

### Related Environment
Please provide the compilation or runtime environment information. 

ubuntu 22.04

**Comment by waruqi** [comment]
try it again.

**Comment by laoshaw** [comment]
works now, thanks!
