### ISSUE TITLE
error loading module 'ltui.lcurses' from file '/usr/local/lib/lua/5.1/ltui.so'

### ISSUE THREAD

**Issue by 4mig4** [tboox/ltui#7]
### Describe the bug

Tried you README.md example code:

```
luajit ./tests/dialog.lua
```

### Error output

```
luajit: error loading module 'ltui.lcurses' from file '/usr/local/lib/lua/5.1/ltui.so':
	/usr/local/lib/lua/5.1/ltui.so: undefined symbol: acs_map
stack traceback:
	[C]: at 0x555821e25fe0
	[C]: in function 'require'
	/usr/local/share/lua/5.1/ltui/curses.lua:31: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/ltui/application.lua:30: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/ltui.lua:31: in main chunk
	[C]: in function 'require'
	./tests/dialog.lua:27: in main chunk
	[C]: at 0x555821dd01d0
```

### Related Environment
- ltui installed with `luarocks install ltui` which yielded:

```
Installing https://luarocks.org/ltui-1.5-1.src.rock

gcc -O2 -fPIC -I/usr/include/lua5.1 -c src/core/lcurses/lcurses.c -o src/core/lcurses/lcurses.o
gcc -shared -o ltui.so src/core/lcurses/lcurses.o
ltui 1.5-1 is now installed in /usr/local (license: Apache-2.0)

```

- Ubuntu 18.04.4 LTS
- LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/

**Comment by waruqi** [comment]
you can try using xmake to build and run it.

xmake
xmake run test dialog

**Comment by waruqi** [comment]
>  undefined symbol: acs_map
gcc -shared -o ltui.so src/core/lcurses/lcurses.o

maybe do not link libncurse or libcurse

**Comment by 4mig4** [comment]
where do you get xmake ? 

But this is from the Luarocks, so you need to fix the lua rock and reupload it once fixed.

https://luarocks.org/modules/waruqi/ltui <----

**Comment by waruqi** [comment]
you can see https://xmake.io/#/guide/installation 

only run the following command to install xmake.

```
bash <(wget https://xmake.io/shget.text -O -)
```

**Comment by waruqi** [comment]
I have fixed it, you can try reinstall it again via luarocks.

**Comment by 4mig4** [comment]
OK it is working now! thanks for fixing it
