### ISSUE TITLE
Missing top white line in most widgets

### ISSUE THREAD

**Issue by 4mig4** [tboox/ltui#8]
Under Linux there is a missing **top white line** in most widgets , please see example below

![Screenshot from 2020-05-06 19-12-59](https://user-images.githubusercontent.com/3671074/81166353-8aa00800-8fce-11ea-84b9-7e0feb6bf221.png)

**Comment by waruqi** [comment]
I have fixed it, you can try it again.

**Comment by 4mig4** [comment]
I confirm it is fixed on the 4 Oses I tested it with (OpenBSD , NetBSD, FreeBSD, Linux)
