### ISSUE TITLE
Widget not drawing box correctly on size different from initial size

### ISSUE THREAD

**Issue by 4mig4** [tboox/ltui#9]
Problems circled in red.

This is using the  `tests/dialog.lua` example:

![Screenshot from 2020-05-06 18-53-24-tip](https://user-images.githubusercontent.com/3671074/81166633-ca66ef80-8fce-11ea-9962-867ffad2a1b4.png)

**Comment by waruqi** [comment]
same problem https://github.com/tboox/ltui/issues/8

**Comment by 4mig4** [comment]
I confirm it is fixed on all 4 OSes I tested ( NetBSD, FreeBSD, OpenBSD, Linux)
